### PR TITLE
scanRooms after currentUser resolves in GBot init

### LINKED ISSUE #97: problems on joining rooms at startup
```
GitterHelper non 200 response from { uri: 'https://gitter.im/api/v1/user/undefined/rooms',
  headers: 
   { 'Content-Type': 'application/json',
     Accept: 'application/json',
     Authorization: 'Bearer 1d8720f6b8373ee5d93e387639db97262b569558' } }
```

### PR DESCRIPTION
**Pull request by dting**
Resolves #97

### CODE REVIEW

**Comment by dting** [comment]
This change completely breaks:

https://github.com/dcsan/gitterbot/blob/master/nap/lib/bot/BotCommands.js#L250

    // FIXME - this isn't working it seems
    rejoin: function (input, bot) {
        clog("GBot", GBot);
        BotCommands.bot.scanRooms();
        return "rejoined";
    },

But, that code doesn't seemed to be hooked up to anything.

**Comment by dcsan** [comment]
thanks for taking a stab at this, its a complex area.

i was chatting with the gitter team about this today, and there are some other options ahead like completely switching the gitter library we use...

**Comment by dcsan** [comment]
rejoin was a method i was calling from the chat originally, when we added new rooms. it was kind of like calling "reboot" for the app to "hot reload" the app and content.

**Comment by dcsan** [comment]
discussion 
https://gitter.im/gitterHQ/developers

another question. when our bot starts up now, i sign into a bunch of rooms
but i get:
body {"error":"API rate limit exceeded"}
so i'm worried some of those rooms aren't actually joined for listening to
wondering if i have to write a complicated routine to buffer those events, or any other work arounds? this only became an issue recently as i added a few more rooms.
after a bit, the app seems to settle down
MadLittleMods 15:02
@dcsan The rest limit is 100 requests per minute. I can look into increasing the limit it slightly for the bot but not sure on this. If you could have some middleware log what requests are going out to the API, then that could give you a good idea of what it is being used up on.
dcsan 15:03
yep i understand. its just at system bootup where i think we login to 40 rooms or so using one key. i just have to let it cool down for a minute or so, which is usually fine, tho it will be nice in future to have a "hot deploy" without waiting.
MadLittleMods 15:06
@dcsan Another possibility is adding the ability to join multiple rooms in a single request. You are using this resource endpoint for joining correct? https://developer.gitter.im/docs/rooms-resource#join-a-room
dcsan 15:07
actually its something i need to rewrite anyway but putting off as it will be moving to your realtime API which looks like a big refactor... but probly worth doing!
its currently left over code from when i was just copy/pasting your samples and its quite a mess. i wasn't sure how to get a room Object, so end up joining, to get a room, to listen to. I think I can just 'listen' if the bot is already joined
dcsan 15:12
currently its around here:
https://github.com/dcsan/gitterbot/blob/master/nap/lib/bot/GBot.js#L303-L308
dcsan 15:17
listenToRoom is with the old streaming client
https://github.com/dcsan/gitterbot/blob/master/nap/lib/bot/GBot.js#L48
dcsan 15:28

**Comment by dting** [comment]
Thanks. I totally neglected to handle the error for that currentUser call. Commented out the `rejoin` command for now.

**Pull request merged**
